### ISSUE TITLE
proxy 0: missing type error

### ISSUE THREAD

**Issue by AliMoal** [mahdibland/V2RayAggregator#18]
Hi, the error `proxy 0: missing type error` will appear while adding [Group2](https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/EternityAir.yml).

**Comment by sadikoji** [comment]
hi
send me proxy

**Comment by AliMoal** [comment]
What is your meaning? 
This is the output file:
```
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
  - 9.9.9.9
  - 1.1.1.1
  - https://dns.google/dns-query
  - tls://dns.google:853
proxies:
- null
proxy-groups:
- name: Global ©️
  type: select
  proxies:
  - Global - UrlTest(Tiers) 🥶
  - Global - Fallback(Tiers) 🌎
  - Global - LoadBalance(ch) 🦄
  - Global - LoadBalance(rr) 🍄
  - Tier 1 🚀
  - Tier 2 ⚡️
  - Tier 3 💎
  - Tier 4 🗿
- name: Global - UrlTest(Tiers) 🥶
  type: url-test
  url: http://clients3.google.com/generate_204
  interval: 300
  proxies:
  - Tier 1 🚀
  - Tier 2 ⚡️
  - Tier 3 💎
  - Tier 4 🗿
- name: Global - Fallback(Tiers) 🌎
  type: fallback
  url: http://clients3.google.com/generate_204
  interval: 300
  proxies:
  - Tier 1 🚀
  - Tier 2 ⚡️
  - Tier 3 💎
  - Tier 4 🗿
- name: Global - LoadBalance(ch) 🦄
  type: load-balance
  strategy: consistent-hashing
  url: http://clients3.google.com/generate_204
  interval: 300
  proxies:
  - Tier 1 🚀
  - Tier 2 ⚡️
  - Tier 3 💎
  - Tier 4 🗿
- name: Global - LoadBalance(rr) 🍄
  type: load-balance
  strategy: round-robin
  url: http://clients3.google.com/generate_204
  interval: 300
  proxies:
  - Tier 1 🚀
  - Tier 2 ⚡️
  - Tier 3 💎
  - Tier 4 🗿
- name: Tier 1 🚀
  type: url-test
  url: http://clients3.google.com/generate_204
  interval: 300
  tolerance: 100
  proxies: []
- name: Tier 2 ⚡️
  type: url-test
  url: http://clients3.google.com/generate_204
  interval: 300
  tolerance: 100
  proxies: []
- name: Tier 3 💎
  type: url-test
  url: http://clients3.google.com/generate_204
  interval: 300
  tolerance: 100
  proxies: []
- name: Tier 4 🗿
  type: url-test
  url: http://clients3.google.com/generate_204
  interval: 300
  tolerance: 100
  proxies:
  - DIRECT
rules:
- MATCH,Global ©️

```
